apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        app: core-microservice-frontend
        kompose.cmd: kompose convert -f docker-compose.yml -o kube-manifest.yaml
        kompose.version: 1.18.0 (06a2e56)
      creationTimestamp: null
      labels:
        io.kompose.service: core-microservice-frontend
      name: core-microservice-frontend
    spec:
      type: NodePort
      ports:
        - name: "4300"
          port: 4300
          targetPort: 80
      selector:
        io.kompose.service: core-microservice-frontend
    status:
      loadBalancer: {}
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      annotations:
        app: core-microservice-frontend
        kompose.cmd: kompose convert -f docker-compose.yml -o kube-manifest.yaml
        kompose.version: 1.18.0 (06a2e56)
      creationTimestamp: null
      labels:
        io.kompose.service: core-microservice-frontend
      name: core-microservice-frontend
    spec:
      replicas: 1
      strategy: {}
      template:
        metadata:
          creationTimestamp: null
          labels:
            io.kompose.service: core-microservice-frontend
        spec:
          containers:
            - image: proflo/core-microservice-frontend:<VERSION>
              name: core-microservice-frontend
              ports:
                - containerPort: 80
              resources: {}
          restartPolicy: Always
    status: {}
  - apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: core-microservice-frontend-ingress
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
    spec:
      rules:
        - host: core.proflo.cgi-wave7.stackroute.io
          http:
            paths:
              - path: /
                backend:
                  serviceName: core-microservice-frontend
                  servicePort: 80
kind: List
metadata: {}
